# Generated by Django 3.0.6 on 2020-05-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('job_des', models.TextField()),
                ('job_sal', models.IntegerField()),
                ('job_loc', models.CharField(max_length=50)),
            ],
        ),
    ]
