# Generated by Django 3.0.7 on 2020-06-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_enquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisationType', models.CharField(choices=[('PAS', 'PlacementAgency'), ('FLS', 'Freelancer'), ('NGO', 'Ngo'), ('TIS', 'TrainingInstitute'), ('CCS', 'CyberCafe'), ('CLG', 'College')], default='PLACEMENT_AGENCY', max_length=3)),
                ('organisationName', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contactNumber', models.IntegerField(max_length=10)),
                ('experience', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='contactNumber',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='contactNumber',
            field=models.IntegerField(max_length=10),
        ),
    ]
