# Generated by Django 3.0.7 on 2020-06-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200620_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contactNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='contactNumber',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='partner',
            name='contactNumber',
            field=models.IntegerField(),
        ),
    ]
