# Generated by Django 3.0.7 on 2020-06-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200620_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='experience',
            field=models.IntegerField(),
        ),
    ]
